# build stage
FROM node:15.11.0-alpine3.10 as build-stage

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp

COPY vue.config.js ./
COPY src/ ./src/

RUN npm run build


# production stage
FROM nginx:1.18.0-alpine-stable as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
