# https://cli.vuejs.org/guide/deployment.html#docker-nginx

# BUILD stage
FROM node:15.11.0-alpine3.10 as build-stage

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp

COPY vue.config.js ./
COPY src/ ./src/
COPY public ./public/
COPY .env.production ./

RUN npm run build

# PRODUCTION stage
FROM nginx:1.19.8-alpine as production-stage

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY /compose/nginx-dev.conf /etc/nginx/nginx-dev.conf

COPY /compose/start.sh /
RUN chmod +x /start.sh
CMD ["/start.sh"]
