FROM node:15.11.0-stretch

RUN npm install -g http-server

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY vue.config.js ./
COPY src/ ./src/

RUN npm run build

EXPOSE 8080

CMD [ "http-server", "dist" ]
