# build stage
FROM node:15.11.0-alpine3.10 as build-stage

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp

COPY vue.config.js ./
COPY src/ ./src/

RUN npm run build

# production stage
FROM nginx:1.19.8-alpine as production-stage
COPY /compose/default.conf /etc/nginx/conf.d/
COPY --from=build-stage /app/dist /usr/share/nginx/html

# https://jonhnes.medium.com/vue-with-docker-since-creation-until-deployment-on-heroku-5b31c8f041a7
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf
