const SET_NOTIFY_ME_CRYPTO_SENT = "SET_NOTIFY_ME_CRYPTO_SENT"
const SET_REGISTER_DATA = "SET_REGISTER_DATA"
const SET_IS_LOGGED = "SET_IS_LOGGED"

export {
    SET_NOTIFY_ME_CRYPTO_SENT,
    SET_REGISTER_DATA,
    SET_IS_LOGGED
}

